### ISSUE TITLE
Profile button on the Packages screen is broken, but working on the Account screen

### ISSUE THREAD

**Issue by asheroto** [chocolatey/home#193] opened 2022-10-03 03:53 UTC
- Go here: https://community.chocolatey.org/packages
- Click "Profile"
- It should give you a 404

- Click on "Account"
- Then click "Profile"
- It should work there

Appears to be working on the individual packages, but not the main listing.

Video shows the difference in the HTML.

https://user-images.githubusercontent.com/49938263/193498603-c4971b2a-41a9-4ad9-8de9-a5286e45cbfe.mp4

**Comment by gep13** [comment] 2022-10-03 12:37
@asheroto thank you for taking the time to report this issue.

This is actually a known issue, which is being tracked here: https://github.com/chocolatey/home/issues/79

As such, I am going to close this issue, and mark it as a duplicate.

Duplicate of #79

**Closed by gep13** 2022-10-03 12:37 UTC
Labels: Duplicate Issue
