### ISSUE TITLE
Images bug

### ISSUE THREAD

**Issue by DavideC03** [chocolatey/home#42] opened 2021-04-03 06:23 UTC
Good morning,
I have a problem with the logo image of my packages.

For a few days, I have not been able to see my project name's logos in "logged in mode".
The strange thing is that if I try to see the same package as "Incognito" it works fine.

I've already tried removing all website data in the main view, but nothing has changed.

Please, can you say me how can fix it?

Thanks,
DavideC03

P.S.
Here you can see the preview of your different results on the same page.
![image](https://user-images.githubusercontent.com/38205382/113470410-b1242880-9455-11eb-98bb-fb150f36c037.png)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1138) by [Unito](https://www.unito.io)

**Comment by virtualex-itv** [comment] 2021-05-18 17:54
@gep13 @AdmiringWorm - been plagued by this same issue on a few packages and the images do not display when looking at my profile page.  Spoke to Kim about this earlier so posting here instead of raising a new issue.  I suspect this has something to do with the caching as some of my package logos have been plagued by this for 6 months to a year, if not longer. Attaching image for reference.
![2021-05-18_11-25-13](https://user-images.githubusercontent.com/12056704/118700328-8b25ce00-b7e0-11eb-8313-a612a0636e55.png)

**Comment by st3phhays** [comment] 2022-05-10 19:30
Possibly related issue https://github.com/chocolatey/home/issues/157

**Comment by pauby** [comment] 2023-05-23 08:39
I'm going to go ahead and close this as a duplicate of #157 as that issue has more information and interaction than this one. They are both related.

**Closed by pauby** 2023-05-23 08:39 UTC
Labels: Bug, CommunityRepository, 0 - _Triaging
