### ISSUE TITLE
Some packages cannot be found by their full names

### ISSUE THREAD

**Issue by jondemon** [chocolatey/home#66] opened 2021-08-05 17:07 UTC
![WindowsTerminal_Irb9xDypPG](https://user-images.githubusercontent.com/1940655/128391595-2397ec4a-3b6d-449a-85cc-bba2c1c5c12a.jpg)

**Comment by corbob** [comment] 2021-08-06 01:30
If I were to guess, I'd say this is a caching or load balancing issue with the community repository. Does it reproduce if you try multiple times? I've been unable to reproduce from my systems

![image](https://user-images.githubusercontent.com/30301021/128442189-4f72e392-4bc2-4062-ae01-575ec4049adf.png)

**Comment by vexx32** [comment] 2021-08-06 03:26
Also worth looking into whether it can be found with `choco list --exact cryptomato`, might help us narrow down where the issue is exactly.

**Comment by corbob** [comment] 2021-08-06 21:13
I just noticed that you used the find command and I only demonstrated the list and search commands. Just to ensure we're all on the same page: these are the same command.
![Screenshot of code snippet showing list, search, and find as aliases for the list command](https://user-images.githubusercontent.com/30301021/128571509-95b3fb13-707c-473a-a29b-9db1cb24d4bf.png)

**Comment by pauby** [comment] 2022-06-04 11:28
There has been no updates to this in some time. I'm going to go ahead and close this issue, but we can reopen it if necessary.

**Closed by pauby** 2022-06-04 11:28 UTC
