### ISSUE TITLE
support formal designation and handling of package conflicts

### ISSUE THREAD

**Issue by davidem00** [chocolatey/home#285] opened 2023-11-17 04:21 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I encountered a conflict between two packages - teamviewer and teamviewer.host
They cannot be installed alongside each other.  The second choco install will fail with some error that does not make it clear what the issue is, only a non-specific Installer error, failing the package install with no advice for how to resolve.

### Describe The Solution. Why is it needed?

Allow package Maintainers to designate known conflicts with other designated packages in the manifest/configuration details of a choco package (with or without version numbers for each) , along with standard options about how they should be handled, giving explicit Error or Warning messages referring to the known conflict.

Some possibilities for handling:
Abort Current Package install (as Error)
Abort Current Package install (as Warning)
Remove Other Package, then Install Current
et al
Prompt User

### Additional Context

the following is the specific error encountered, as an example of what could be handled through formal Conflict Management, instead:  (see also the Discussion section of the Community Repository package page)
----

Installing teamviewer...
WARNING: Setup was cancelled.
ERROR: Running ["c:\public_repository\installers\packages\chocolatey\teamviewer\15.47.3\TeamViewer_Setup_x64.exe" /S ] was not successful. Exit code was '2'. Exit code indicates the following: Setup was cancelled..
The install of teamviewer was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\teamviewer\tools\chocolateyInstall.ps1'.
See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- teamviewer (exited 2) - Error while running 'C:\ProgramData\chocolatey\lib\teamviewer\tools\chocolateyInstall.ps1'.
See log for details.

---

"the log" has no further explanation of the issue.

Uninstalling [teamviewer.host](http://disq.us/url?url=http%3A%2F%2Fteamviewer.host%3AAd1ykMcggD_TNWyqUWhcu7lJYAg&cuid=2163236) allows this package to be installed (I believe this package has the "host" features included - the host version is for installation on remote machines)

**Comment by pauby** [comment] 2023-12-23 14:48
This looks to be a duplicate of https://github.com/chocolatey/choco/issues/1877

**Closed by pauby** 2023-12-23 14:48 UTC
