### ISSUE TITLE
chocolatey.org API returns bogus package versions

### ISSUE THREAD

**Issue by slonopotamus** [chocolatey/home#159] opened 2022-05-11 13:06 UTC
### What You Are Seeing?

chocolatey.org API returns bogus package versions.

### What is Expected?

https://community.chocolatey.org/packages/stevedore has latest version of `0.6.1`. However, if one queries latest version via chocolatey.org API then they get unrelated data

### How Did You Get This To Happen? (Steps to Reproduce)

Open `https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true`

Expected: you get info about `stevedore` version `0.6.1`.

Actual: you're redirected to some other random package (often, it is either `notepadplusplus`, `openjdk` or `7zip`).

Downstream issue: https://github.com/badges/shields/issues/7931

https://img.shields.io/chocolatey/v/stevedore
![](https://img.shields.io/chocolatey/v/stevedore)

### Output Log

```sh
$ curl -I "https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true"
HTTP/2 301 
date: Wed, 11 May 2022 12:58:16 GMT
content-type: text/html
location: https://chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'notepadplusplus')%20and%20IsLatestVersion&includePrerelease=false&$top=100&includeAllVersions=false
x-github-request-id: 6B0A:3AD6:333709:350E53:627BA4F7
accept-ranges: bytes
via: 1.1 varnish
age: 3569
x-served-by: cache-hhn4058-HHN
x-cache: HIT
x-cache-hits: 2
x-timer: S1652273897.637157,VS0,VE0
vary: Accept-Encoding
x-fastly-request-id: 708c1e7113f70f2d7df9c0515b0a8169138ff579
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
server: cloudflare
cf-ray: 709b15cddda7900a-FRA
```

**Comment by slonopotamus** [comment] 2022-05-11 14:19
> The only supported method of querying the Chocolatey Community Repository is using Chocolatey CLI or Chocolatey.Lib

I doubt either of these is suitable for https://shields.io/

@calebcartwright I'm not sure how to proceed from here.

**Comment by pauby** [comment] 2022-05-11 15:16
Just to follow-up, your query works for me and another member of the team. So regardless of it not being supported, the issue doesn't look to be at Chocolatey's side.

```
HTTP/1.1 301 Moved Permanently
Date: Wed, 11 May 2022 15:13:07 GMT
Content-Type: text/html
Connection: keep-alive
location: https://chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true
x-github-request-id: A962:3F0D:1E658A:31AE76:627BD132
accept-ranges: bytes
via: 1.1 varnish
age: 337
x-served-by: cache-lcy19220-LCY
x-cache: HIT
x-cache-hits: 1
x-timer: S1652281988.547203,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: ed19992be4ea87439cd654eeb03b1d20a52566e5
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=12960000
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 709bdb55e8c2067e-LHR
```

Does it make any difference if you use `community.chocolatey.org` instead of `chocolatey.org` (`chocolatey.org` is no longer the Chocolatey Community Repository).

**Comment by calebcartwright** [comment] 2022-05-11 15:41
We're a bit bifurcated across two different issues now but will respond to a few items here:

> Just to follow-up, your query works for me and another member of the team. So regardless of it not being supported, the issue doesn't look to be at Chocolatey's side

We'd noted the same on our end, with the redirects working for those in certain geos while issuing a bad redirect for requests originating from other geos. I'm still readily able to consistently reproduce the bad redirect behavior (from the US), while my colleague in the UK is getting a good redirect. That still sounds like an issue on the Chocolatey side to me.

> The only supported method of querying the Chocolatey Community Repository is using Chocolatey CLI or Chocolatey.Lib. Direct queries against the website are not guaranteed to work.

Hmm. I can understand this in terms of what the chocolatey team recommends/is willing to support/etc., but I'd have to assume that the distributed executable and sdk are both still reliant on the same backend API, no?

From the Shields side, we integrate with a large number of backends via their APIs, and have been using the Chocolatey API (which I believe is the standard NuGet API?) successfully for quite some time. The current redirect issue is a fairly new phenomenon, but if you have concerns with us consuming the API in general then please let us know so we can react accordingly, including dropping our support for Chocolatey badges if need be, as we want to ensure we're being good citizens/consumers too!

**Comment by slonopotamus** [comment] 2022-05-11 15:46
> We'd noted the same on our end, with the redirects working for those in certain geos while issuing a bad redirect for requests originating from other geos.

Interestingly, I'm observing both good and bad behavior from the same machine in Frankfurt.

Good

```
$ curl -I 'https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true'
HTTP/2 301 
date: Wed, 11 May 2022 15:42:56 GMT
content-type: text/html
location: https://chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true
x-github-request-id: 2E2C:AEA2:85947E:898A65:627BD97D
accept-ranges: bytes
via: 1.1 varnish
age: 3
x-served-by: cache-hhn4072-HHN
x-cache: HIT
x-cache-hits: 1
x-timer: S1652283777.631065,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: 6280d2046e891d445c817cb47774ef1c72dc44cf
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
server: cloudflare
cf-ray: 709c0703c9d36949-FRA
```

Bad (just a second later!)

```
$ curl -I 'https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true'
HTTP/2 301 
date: Wed, 11 May 2022 15:42:57 GMT
content-type: text/html
location: https://chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'jq')%20and%20IsLatestVersion&includePrerelease=false&$top=100&includeAllVersions=false
x-github-request-id: 3B0C:9B58:12E46A:151D53:627BD153
accept-ranges: bytes
via: 1.1 varnish
age: 2094
x-served-by: cache-fra19179-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1652283778.701284,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: 9b9a9ef23e5b4090fbdd1f2030f8da1e08218c53
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
server: cloudflare
cf-ray: 709c070a7a59917a-FRA
```

----

Wild guess: could this be related to HTTP/2? I noticed that both @calebcartwright and me use HTTP/2, but @pauby uses HTTP/1.1

**Comment by pauby** [comment] 2022-05-11 17:10
The issues are not the consumption of the API but with the direct queries to oData. We reserve the right to change or break behaviour in the Chocolatey API.

The Chocolatey Community Repository is intended to be queried and used by Chocolatey CLI and Chocolatey.Lib. If you're using it another way, we can't support that. Your queries may work now, but YMMV in future.

**Comment by pauby** [comment] 2022-05-11 17:12
I'm going to go ahead and close this issue as you're unblocked. However, we can always open it again if need be.

**Closed by pauby** 2022-05-11 17:13 UTC
