### ISSUE TITLE
Random Capitalization in chocolatey.org

### ISSUE THREAD

**Issue by naveen521kk** [chocolatey/home#27] opened 2021-03-19 18:39 UTC
In https://chocolatey.org I could see things randomly switched to Upper case and looks ugly. For example,

* On a package, I maintain, [TinyTeX](https://chocolatey.org/packages/tinytex), where on the title it is displayed as `TINYTEX`
![image](https://user-images.githubusercontent.com/49693820/111826783-1e40a580-890f-11eb-99d7-53eafdbd68f5.png)
Also, this problem happens in the [Description section](https://chocolatey.org/packages/tinytex#description)
![image](https://user-images.githubusercontent.com/49693820/111826999-61027d80-890f-11eb-8f4e-55cda97f06fc.png)
The same things apply to other packages I randomly visit as well. For example, [`TexLive`](https://chocolatey.org/packages/TexLive), I am most picky about `LaTeX` packages because the case is important over there.
![image](https://user-images.githubusercontent.com/49693820/111827655-277e4200-8910-11eb-907f-4e50b84d8436.png)

* Same things happen to profiles also, for example, https://chocolatey.org/profiles/naveen521kk
![image](https://user-images.githubusercontent.com/49693820/111827622-1b928000-8910-11eb-881a-c67710e39d12.png)

## Fix
This fix should as simple as removing 

```css
text-transform: uppercase;
```

from all the `<h1>` tags.

Thanks.

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/chocolatey-software/community.chocolatey.org/-/issues/1072) by [Unito](https://www.unito.io/learn-more)

**Comment by naveen521kk** [comment] 2021-03-19 18:43
If I am picking the right repository (sorry I don't know because it doesn't have a readme or something), then it should be removing 

https://github.com/chocolatey/choco-theme/blob/main/scss/_base.scss#L23-L25
```css
h1 {
    text-transform: uppercase;
}
```

**Comment by designxsteph** [comment] 2021-03-23 01:49
Hi there @naveen521kk , thanks for the report! While making the `<h1>` tags was done by design throughout the entire site, I can see how it does look odd/confusing in some scenarios, such as the package titles you mentioned. I will get in a fix for this case.

**Comment by gep13** [comment] 2021-03-24 08:05
@naveen521kk a new version of the site has now been released which fixes the issue that was raised here.  Thanks for bringing this to our attention.

**Closed** 2021-03-24 08:04 UTC
Labels: 5 - Released, CommunityRepository

**Comment by naveen521kk** [comment] 2021-03-26 11:42
Thank You :)
