### ISSUE TITLE
406 trying to access https://chocolatey.org/install.ps1

### ISSUE THREAD

**Issue by olabacker** [chocolatey/home#58] opened 2021-06-04 06:07 UTC
I've installed chocolatey many times but today it seems I'm getting a 406 trying to access the installer script at https://chocolatey.org/install.ps1.

Anyone else getting this or just me?

**Comment by Windos** [comment] 2021-06-04 08:32
Hey @olabacker, I'm not able to reproduce here. Have you retried and is it still an issue?

Also does it load for you in a browser?

**Comment by olabacker** [comment] 2021-06-04 08:42
Stange. Still an issue.

Tried accessing it on another computer which I have choco installed since before, it is also giving me 406 now. Also tried on my phone (on another isp and no cache), still the same.

**Comment by olabacker** [comment] 2021-06-04 08:42
The message given trying to access it from a browser is this:

406 - Client browser does not accept the MIME type of the requested page.
The page you are looking for cannot be opened by your browser because it has a file name extension that your browser does not accept.

**Comment by Windos** [comment] 2021-06-04 08:52
Does https://community.chocolatey.org/ open ok for you?

**Comment by olabacker** [comment] 2021-06-04 08:56
Yes, all pages seem okay. Also tried accessing this link for testing https://chocolatey.org/installchocolatey.cmd which is supposed to exist according to https://docs.chocolatey.org/en-us/choco/setup#install-using-powershell-from-cmd.exe. This however gives me 404.

**Comment by JPRuskin** [comment] 2021-06-04 09:17
For the Cmd file, that appears to be case sensitive - try [https://chocolatey.org/installChocolatey.cmd](https://chocolatey.org/installChocolatey.cmd). We'll fix the documentation! :)

**Comment by Windos** [comment] 2021-06-04 09:38
Sorry for the 20 questions, @olabacker, just trying to narrow things down a bit 😀

I've made some changes at our end, could I get you to try again (possibly with a hard refresh)?

If it's still not working:

* What browser are you using?
* Any AV software? Firewall? VPN?

**Comment by olabacker** [comment] 2021-06-04 10:06
No worries! 

Still not working with my isp. I tried a couple of different setups, and it worked connecting with vpn.. 

* default win10 - 406
* another computer same network - 406
* isp on phone - 406
* work computer (another isp) - 200
* using vpn provider (ovpn) - 200

Disabling/enabling vpn returns 406/200 directly after, no need to clear anything.

The default setup is a newly setup win10 pro, tested with a couple different browsers, without vpn, default firewall config, no av sw.

**Comment by olabacker** [comment] 2021-06-04 10:07
Thanks for fixing the other link by the way.

**Comment by Windos** [comment] 2021-06-04 10:32
Could I get you to fill out this form (best way to get your IP address, rather than asking for it here): https://chocolatey.org/contact/blocked-ip-address

I'll see if I can see anything from the perspective, just mention this issue in the comment so I know to match them up.

**Comment by IzaacJ** [comment] 2021-06-06 18:33
Same issue here on a fresh install of Windows 10, 20H2. I haven't installed anything, just removed all the UWP apps I won't use (Candy Crush, Skype etc).
I installed it just fine on my desktop the day before yesterday, with a fresh install of W10 10H2, but with some additional software installed (VSCode, Spotify non-UWP, Skype non-UWP, Chrome).

**Comment by gep13** [comment] 2021-06-07 08:37
@IzaacJ can you please confirm the exact steps that you are following when you see this error happeing?

**Comment by IzaacJ** [comment] 2021-06-07 09:02
@gep13 `406 - Client browser does not accept the MIME type of the requested page.` when visiting https://chocolatey.org/install.ps1 directly in Edge (on the laptop) or Google Chrome (on the desktop), and
```ps
Exception calling "DownloadString" with "1" argument(s): "Fjärrservern returnerade ett fel: (406) Inte accepterat."
At line:1 char:166
+ ...  -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('ht ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
when running `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))` in PowerShell (admin mode) on both the laptop and the desktop. The desktop did however successfully install Chocolatey a few days ago.

**Comment by gep13** [comment] 2021-06-07 09:04
@IzaacJ just to rule something out, can I get you to try the following:

```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

This simply removes a redirect for this file from chocolatey.org to community.chocolatey.org

**Comment by IzaacJ** [comment] 2021-06-07 09:06
@gep13 Still the same error sadly :/

**Comment by gep13** [comment] 2021-06-07 09:07
@IzaacJ that error that we are seeing here is specifically for the download of this specific file, the `install.ps1` file, and so far, the only problems are when the request is coming through Sweden. We are trying to isolate what is going on here, and what we can do to rectify this.

**Comment by IzaacJ** [comment] 2021-06-07 09:12
@gep13 Oh, so it is specific to Sweden? :O I could get in contact with my ISP (Telenor/Bredbandsbolaget) and see if they have any knowledge. Or could it be about the locale in Windows? I know I had some issues with Excel when I had English as locale and Swedish for keyboard and spellchecking.

**Comment by gep13** [comment] 2021-06-07 09:16
@IzaacJ the short answer is that we don't know anything for sure yet. Based on what we can see in our logs, all the requests that are failing are coming via Sweden, and that is all we know for sure. We are trying to replicate the problem just now, and will follow up here once we know more.

**Comment by olabacker** [comment] 2021-06-07 09:22
Not sure if it per ISP even since both my phone isp and home isp is failing whilst my work computer can access it. Phone is using isp vimla/telenor but both home and work computer have the same isp (bahnhof).

**Comment by IzaacJ** [comment] 2021-06-07 09:32
I have Telenor on the fibre and on my mobile devices (got both iOS and Android phones and tablets), and got the same error on all devices.

**Comment by JPRuskin** [comment] 2021-06-07 11:04
@IzaacJ @olabacker We think we've got a handle on it - do you mind testing and seeing if it's still an issue?

**Comment by olabacker** [comment] 2021-06-07 11:10
Yes, it is now working on all my configurations! What was changed? Thanks

**Comment by JPRuskin** [comment] 2021-06-07 11:29
It seems someone managed to get (and cache) a 406 response for that one file late last week, via the datacenter in Stockholm. We purged it from that cache, and it's now returning the correct response to anyone routed there.

Closing this issue now, as we seem to have agreement from >50% of reporting parties (from GitHub, Gitter, tickets, etc) that it's fixed. If not, please reply and we'll continue investigating.

**Comment by IzaacJ** [comment] 2021-06-07 12:28
Working fine for me too 👍

**Comment by stahlhenrik** [comment] 2021-08-22 10:24
Swedish user here. Same issue today (Aug 22). Could work around by using VPN via US.

**Comment by 2000dB** [comment] 2021-08-22 19:01
Swedish user here as well, started getting this error yesterday

**Comment by gep13** [comment] 2021-08-22 19:59
@stahlhenrik @2000dB can I please get you to try again, and let me know if you are still having the same problem?

**Comment by stahlhenrik** [comment] 2021-08-22 20:08
works for me now - aug 22, 22:07 CEST. Thanks!

**Comment by gep13** [comment] 2021-08-22 20:22
@stahlhenrik thank you for confirming!

**Comment by 0ax1** [comment] 2021-09-05 16:19
Getting the same issue as of today, location being Stockholm. (https://github.com/chocolatey/home/issues/58#issuecomment-855847419)

**Comment by JPRuskin** [comment] 2021-09-05 20:03
Should be worked-around for now, @0ax1

**Comment by 0ax1** [comment] 2021-09-05 21:17
Great, thanks for the quick response and fix! Seems to be working for the moment.

**Comment by NocnyBlack** [comment] 2022-04-15 18:28
hey, i have the same issue, 406 error durning installation. I'm from Poland.

**Comment by Windos** [comment] 2022-04-15 23:16
@NocnyBlack please try again now

**Comment by NocnyBlack** [comment] 2022-04-16 19:40
@Windos It's working now, thank you!

**Closed** 2022-06-04 11:31 UTC
Labels: 0 - _Triaging
