### ISSUE TITLE
pin versions by Semantic Version number range

### ISSUE THREAD

**Issue by davidem00** [chocolatey/home#284] opened 2023-11-17 01:16 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

currently can only restrict installations to specific versions, as opposed to version ranges

in one case, may possess a license only for v3.x of a product (with any minor version upgrades included), but v4.x has also been released on its own maintenance path

also allows for automatic installation/upgrade of broken packages once a known good version becomes available, skipping any auto-packaged versions beforehand

### Describe The Solution. Why is it needed?

allow pins to specify ranges (maybe with wildcards).
allow upgrade command to operate within a range, but be ignored outside of it

Should allow specification covering versions that aren't necessarily installed yet

### Additional Context

e.g.
:: skips any subsequent updates until v4.*, say, for a product that is broken for a given version range
choco pin add -n igdm --version="'>4.*"

:: allows installation/upgrade of subsequent packages for applicable Major version
choco pin add -n beyondcompare --version="'<4.0'"
(alternatively)
choco pin add -n beyondcompare --version="''3.*'"

**Comment by TheCakeIsNaOH** [comment] 2023-11-17 01:37
This is a duplicate of https://github.com/chocolatey/choco/issues/1278

**Comment by davidem00** [comment] 2023-11-17 01:43
Lol.  I searched through Open issues for "pin", and only two came up, not including this one.

The funny part is the OP being motivated by the same product that I am : beyondcompare

**Comment by davidem00** [comment] 2023-11-17 01:47
Oh, I see.  It's in the "choco" repo, not "home". ffs.  No good deed...

**Closed** 2023-12-23 14:49 UTC
Labels: Duplicate Issue, Invalid / Not Issue / No repro / Not Implementing
