### ISSUE TITLE
Some community pages don't work

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [chocolatey/home#296] opened 2024-02-04 03:26 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

First reported in https://github.com/TheCakeIsNaOH/chocolatey-packages/issues/32.

The package installs fine, but the webpage hasn't worked for a month now.

![302073466-f8eacec5-b351-45b8-a654-1c8d783a13e9](https://github.com/chocolatey/home/assets/69355938/a5f805ec-757b-4630-91d1-827cfffb9a13)

### What is Expected?

A working page with up-to-date information.

### How Did You Get This To Happen?

Open https://community.chocolatey.org/packages/pcsx2-dev

### System Details

...

### Installed Packages

```bash
...
```

### Output Log

```bash
...
```

**Comment by pauby** [comment] 2024-02-04 08:11
Thanks for reporting this. That is very strange but I am able to reproduce it on mobile.

![Screenshot_20240204_080958_Firefox Nightly.jpg](https://github.com/chocolatey/home/assets/12760779/4c9fe6aa-fc2b-46db-96a9-cc574bd98fd3)

Let me pick this up internally.

**Comment by TheCakeIsNaOH** [comment] 2024-05-17 14:32
Seems to be fixed now?

**Comment by corbob** [comment] 2024-05-17 14:57
Ah yeah, looking at that package page and the number of versions (my javascript skills tell me it's about 919 listed versions?) it would have been related to the same issue as the zoom package reported in #315.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment] 2024-05-17 16:18
Yes, it's working now.

**Closed** 2024-05-17 16:17 UTC
Labels: Bug

**Comment by corbob** [comment] 2024-05-17 16:49
Duplicate of #315
